[build]
  command = "" # build desativado (Tailwind via CDN)
  publish = "."

[build.environment]
  NODE_VERSION = "20"

# Optional: pretty URLs
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
